apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: olcha-ingress
  namespace: olcha
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/websocket-services: "olcha-go"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - olchaai.com
        - www.olchaai.com
        - api.olchaai.com
      secretName: olcha-tls
  rules:
    - host: olchaai.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-server
                port:
                  number: 8080
          - path: /go
            pathType: Prefix
            backend:
              service:
                name: olcha-go
                port:
                  number: 8082
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus
                port:
                  number: 3000
