import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import authRouter from "./auth";
import usersRouter from "./users";
import postsRouter from "./posts";
import reelsRouter from "./reels";
import storiesRouter from "./stories";
import messagesRouter from "./messages";
import groupsRouter from "./groups";
import notificationsRouter from "./notifications";
import aiRouter from "./ai";
import adminRouter from "./admin";
import stripeRouter from "./stripe";
import moderationRouter from "./moderation";
import goRouter from "./go";
import mediaRouter from "./media";
import walletRouter from "./wallet";
import liveRouter from "./live";
import giftsRouter from "./gifts";
import creatorRouter from "./creator";
import searchRouter from "./search";
import marketplaceRouter from "./marketplace";
import openaiChatRouter from "./openai-chat";
import libraryRouter from "./library";
import voiceCommentsRouter from "./voiceComments";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(postsRouter);
router.use(reelsRouter);
router.use(storiesRouter);
router.use(messagesRouter);
router.use(groupsRouter);
router.use(notificationsRouter);
router.use(aiRouter);
router.use(adminRouter);
router.use(stripeRouter);
router.use(moderationRouter);
router.use("/go", goRouter);
router.use("/media", mediaRouter);
router.use(walletRouter);
router.use(liveRouter);
router.use(giftsRouter);
router.use(creatorRouter);
router.use(searchRouter);
router.use(marketplaceRouter);
router.use(openaiChatRouter);
router.use(libraryRouter);
router.use(voiceCommentsRouter);

export default router;
