import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import authRouter from "./auth";
import usersRouter from "./users";
import postsRouter from "./posts";
import reelsRouter from "./reels";
import storiesRouter from "./stories";
import messagesRouter from "./messages";
import groupsRouter from "./groups";
import notificationsRouter from "./notifications";
import aiRouter from "./ai";
import adminRouter from "./admin";
import stripeRouter from "./stripe";
import moderationRouter from "./moderation";
import goRouter from "./go";
import mediaRouter from "./media";
import walletRouter from "./wallet";
import liveRouter from "./live";
import giftsRouter from "./gifts";
import creatorRouter from "./creator";
import searchRouter from "./search";
import marketplaceRouter from "./marketplace";
import openaiChatRouter from "./openai-chat";
import libraryRouter from "./library";
import voiceCommentsRouter from "./voiceComments";
import gamificationRouter from "./gamification";
import coviewRouter from "./coview";
import anonRouter from "./anon";
import scenariosRouter from "./scenarios";
import moodRouter from "./mood";
import aiTwinRouter from "./aiTwin";
import factCheckRouter from "./factCheck";
import coSpacesRouter from "./coSpaces";
import translateRouter from "./translate";
import muniAiRouter from "./muniAi";
import voiceTranslateRouter from "./voiceTranslate";
import nexusCoreRouter from "./nexusCore";
import platformCostsRouter from "./platformCosts";
import aiAutopilotRouter from "./aiAutopilot";
import monetizationRouter from "./monetization";
import gifsRouter from "./gifs";
import treasuryRouter from "./treasury";
import aiAdminActionsRouter from "./aiAdminActions";
import securityRouter from "./security";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(postsRouter);
router.use(reelsRouter);
router.use(storiesRouter);
router.use(messagesRouter);
router.use(groupsRouter);
router.use(notificationsRouter);
router.use(aiRouter);
router.use(adminRouter);
router.use(stripeRouter);
router.use(moderationRouter);
router.use("/go", goRouter);
router.use("/media", mediaRouter);
router.use(walletRouter);
router.use(liveRouter);
router.use(giftsRouter);
router.use(creatorRouter);
router.use(searchRouter);
router.use(marketplaceRouter);
router.use(openaiChatRouter);
router.use(libraryRouter);
router.use(voiceCommentsRouter);
router.use(gamificationRouter);
router.use(coviewRouter);
router.use(anonRouter);
router.use(scenariosRouter);
router.use(moodRouter);
router.use(aiTwinRouter);
router.use(factCheckRouter);
router.use(coSpacesRouter);
router.use(translateRouter);
router.use(muniAiRouter);
router.use(voiceTranslateRouter);
router.use(nexusCoreRouter);
router.use(platformCostsRouter);
router.use(aiAutopilotRouter);
router.use(monetizationRouter);
router.use(gifsRouter);
router.use(treasuryRouter);
router.use(aiAdminActionsRouter);
router.use(securityRouter);

export default router;
