// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/profile/DarkMatter.tsx": () => import("../components/mockups/profile/DarkMatter.tsx"),
  "./components/mockups/profile/SignalIdentity.tsx": () => import("../components/mockups/profile/SignalIdentity.tsx")
};
